#nested dictionary with all the rooms available for booking

rooms = {
    'L019':{'type':'petit', 'personnes':12, 'aile':'L', 'numero':19, 'lettre':''},
     'L026':{'type':'petit', 'personnes':10, 'aile':'L', 'numero':26, 'lettre':''},
     'L209':{'type':'petit', 'personnes':18, 'aile':'L', 'numero':209, 'lettre':''},
     'L210':{'type':'petit', 'personnes':18, 'aile':'L', 'numero':210, 'lettre':''},
     'L211':{'type':'petit', 'personnes':18, 'aile':'L', 'numero':211, 'lettre':''},
     'L227':{'type':'petit', 'personnes':18, 'aile':'L', 'numero':227, 'lettre':''},
     'L228':{'type':'petit', 'personnes':18, 'aile':'L', 'numero':228, 'lettre':''},
     'L313':{'type':'petit', 'personnes':20, 'aile':'L', 'numero':313, 'lettre':''},
     'L318':{'type':'petit', 'personnes':16, 'aile':'L', 'numero':318, 'lettre':''},
     'L319':{'type':'petit', 'personnes':16, 'aile':'L', 'numero':319, 'lettre':''},
     'L321':{'type':'petit', 'personnes':16, 'aile':'L', 'numero':321, 'lettre':''},
     'L322':{'type':'petit', 'personnes':16, 'aile':'L', 'numero':322, 'lettre':''},
     'BIBLIO':{'type':'moyen', 'personnes':30, 'aile':'V', 'numero':105, 'lettre':''},
     'L027':{'type':'moyen', 'personnes':28, 'aile':'L', 'numero':27, 'lettre':''},
     'L213':{'type':'moyen', 'personnes':48, 'aile':'L', 'numero':213, 'lettre':''},
     'L218':{'type':'moyen', 'personnes':48, 'aile':'L', 'numero':218, 'lettre':''},
     'L224':{'type':'moyen', 'personnes':48, 'aile':'L', 'numero':224, 'lettre':''},
     'L226':{'type':'moyen', 'personnes':30, 'aile':'L', 'numero':226, 'lettre':''},
     'L312':{'type':'moyen', 'personnes':30, 'aile':'L', 'numero':312, 'lettre':''},
     'L316':{'type':'moyen', 'personnes':32, 'aile':'L', 'numero':316, 'lettre':''},
     'V106B':{'type':'moyen', 'personnes':33, 'aile':'V', 'numero':106, 'lettre':'B'},
     'V124':{'type':'moyen', 'personnes':24, 'aile':'V', 'numero':124, 'lettre':''},
     'V106A':{'type':'grand', 'personnes':64, 'aile':'V', 'numero':106, 'lettre':'A'},
     'V107':{'type':'grand', 'personnes':132, 'aile':'V', 'numero':107, 'lettre':''},
     'V005A':{'type':'projet', 'personnes':12, 'aile':'V', 'numero':5, 'lettre':'A'},
     'V005B':{'type':'projet', 'personnes':10, 'aile':'V', 'numero':5, 'lettre':'B'},
     'V005C':{'type':'projet', 'personnes':5, 'aile':'V', 'numero':5, 'lettre':'C'},
     'V005D':{'type':'projet', 'personnes':5, 'aile':'V', 'numero':5, 'lettre':'D'},
     'V334':{'type':'projet', 'personnes':50, 'aile':'V', 'numero':334, 'lettre':''},
     'V335':{'type':'projet', 'personnes':25, 'aile':'V', 'numero':335, 'lettre':''},
     'V111':{'type':'mixte', 'personnes':12, 'aile':'V', 'numero':111, 'lettre':''},
     'V112':{'type':'mixte', 'personnes':18, 'aile':'V', 'numero':112, 'lettre':''},
     'V115':{'type':'mixte', 'personnes':32, 'aile':'V', 'numero':115, 'lettre':''},
     'V116':{'type':'mixte', 'personnes':32, 'aile':'V', 'numero':116, 'lettre':''},
     'V119':{'type':'mixte', 'personnes':20, 'aile':'V', 'numero':119, 'lettre':''}
}  